name = "Hypickle Pack"
author = "Onkoe"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec0b5861bd93e2c5becaeaee933f59e0bd5ffe069d8b437f3f0c3c8ac0e9d7a8"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
