name = "Hypickle Pack"
author = "Onkoe"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e5f930b41a59367ef011331cd69067c1ab3c2128333d259cf3ba828ad22d4b8"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
